modLoader = "javafml"
loaderVersion = "[2,)"
license = "Ultreon API License v1.2"
issueTrackerURL = "https://gitlab.com/ultreon/ultreon-mod-lib/-/issues"

[[mixins]]
config = "ultreonlib-common.mixins.json"

[[mixins]]
config = "ultreonlib.mixins.json"

# The main mod, and all sub-mods.
[[mods]]
modId = "ultreonlib"
version = "${version}"
displayName = "Ultreon Modding Library"
#updateJSONURL="http://myurl.me/"
displayURL = "https://gitlab.com/ultreon/ultreon-mod-lib"
logoFile="ultreonlib.png"
credits = ""
authors = "XyperCode"
description = """
${description}
"""

# Dependencies for the main mod.
[[dependencies.ultreonlib]]
modId = "neoforge"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ultreonlib]]
modId = "minecraft"
versionRange = "1.20.4"
ordering = "NONE"
side = "BOTH"

[[dependencies.ultreonlib]]
modId = "architectury"
versionRange = "[11,12)"
ordering = "NONE"
side = "BOTH"
